// Package main provides a code generator for CloudEventHeader field accessors.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"reflect"
	"strings"
	"text/template"

	"github.com/DIMO-Network/cloudevent/ce"
	"github.com/DIMO-Network/model-garage/pkg/codegen"
)

// CloudeventHeadersToColumnMap is a map of cloudevent header json fields to Clickhouse columns.
var CloudeventHeadersToColumnMap = map[string]struct{}{
	"specversion":     {},
	"subject":         {},
	"time":            {},
	"type":            {},
	"id":              {},
	"source":          {},
	"producer":        {},
	"datacontenttype": {},
	"dataversion":     {},
	"extras":          {},
}

// FieldInfo contains information about a field in the CloudEventHeader.
type FieldInfo struct {
	// FieldName is the name of the field in the CloudEventHeader struct.
	FieldName string
	// JSONName is the name of the field in the JSON tag.
	JSONName string
	// GoType is the type of the field as a string.
	GoType reflect.Type
	// Kind is the kind of the field.
	Kind string
	// Options contains the options for the field generation.
	Options Options
}

// TemplateData contains all the data needed for template generation.
type TemplateData struct {
	// NonColumnFields is a list of fields that are not columns in Clickhouse.
	NonColumnFields []FieldInfo
}

func main() {
	// Parse command line arguments
	outputFile := flag.String("output", "ce/field_accessors_gen.go", "Output file path for generated code")
	flag.Parse()

	// Get information about CloudEventHeader fields
	headerType := reflect.TypeOf(cloudevent.CloudEventHeader{})

	var nonColumnFields []FieldInfo

	for i := 0; i < headerType.NumField(); i++ {
		field := headerType.Field(i)

		jsonName := getJSONFieldName(field)
		if jsonName == "" {
			continue
		}
		genOptions := getCloudEventOptions(field)
		// Skip defined column fields
		if _, ok := CloudeventHeadersToColumnMap[jsonName]; ok {
			continue
		}

		nonColumnFields = append(nonColumnFields, FieldInfo{
			FieldName: field.Name,
			JSONName:  jsonName,
			GoType:    field.Type,
			Kind:      field.Type.Kind().String(),
			Options:   genOptions,
		})
	}

	// Prepare template data
	data := TemplateData{
		NonColumnFields: nonColumnFields,
	}

	// Create template
	tmpl, err := template.New("accessors").Parse(codeTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	// Generate code
	var buff bytes.Buffer

	err = tmpl.Execute(&buff, data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}
	err = codegen.FormatAndWriteToFile(buff.Bytes(), *outputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error formatting and writing to file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated field accessors in %s\n", *outputFile)
}

// getJSONFieldName extracts the JSON field name from a struct field tag
func getJSONFieldName(field reflect.StructField) string {
	tag := field.Tag.Get("json")
	if tag == "" {
		return ""
	}

	name := tag
	if comma := strings.Index(tag, ","); comma != -1 {
		name = tag[:comma]
	}

	if name == "-" {
		return ""
	}

	return name
}

type Options struct {
	// LeaveInExtras indicates that the field should be left in the Extras map.
	LeaveInExtras bool
}

// getCloudEventOptions extracts the CloudEventOptions from a struct field tag
func getCloudEventOptions(field reflect.StructField) Options {
	opts := Options{}
	tag := field.Tag.Get("cloudevent")
	if tag == "" {
		return opts
	}
	optValues := strings.Split(tag, ",")
	for _, opt := range optValues {
		switch opt {
		case "leaveInExtras":
			opts.LeaveInExtras = true
		}
	}
	return opts
}

// Define the template for the generated code
const codeTemplate = `// Code generated by go run cmd/codegen/main.go; DO NOT EDIT.

package cloudevent

// RestoreNonColumnFields restores non-column fields from Extras.
func RestoreNonColumnFields(event *CloudEventHeader) {
	event.SpecVersion = SpecVersion
	if event.Extras != nil {
		delete(event.Extras, "specversion")
	}
	if len(event.Extras) == 0 {
		return
	}
	{{ range .NonColumnFields -}}
	// Restore {{ .FieldName }} field
	if val, ok := event.Extras["{{ .JSONName }}"]; ok {
		{{ if eq .GoType.String "time.Time" -}}
		if timeStr, ok := val.(string); ok {
			if t, err := time.Parse(time.RFC3339, timeStr); err == nil {
				event.{{ .FieldName }} = t
				{{ if not .Options.LeaveInExtras -}}
					delete(event.Extras, "{{ .JSONName }}")
				{{ end -}}
			}
		} else if t, ok := val.(time.Time); ok {
			event.{{ .FieldName }} = t
			{{ if not .Options.LeaveInExtras -}}
				delete(event.Extras, "{{ .JSONName }}")
			{{ end -}}
		}
		{{ else if eq .Kind "slice" -}}
		if anySlice, ok := val.([]any); ok {
			typedSlice := make({{ .GoType.String }}, len(anySlice))
			for i, v := range anySlice {
				typedSlice[i] = v.({{ .GoType.Elem.String }})
			}
			event.{{ .FieldName }} = typedSlice
		}
		{{ else -}}
		if typedVal, ok := val.({{ .GoType.String }}); ok {
			event.{{ .FieldName }} = typedVal
		}
		{{ end -}}
		{{ if not .Options.LeaveInExtras -}}
		delete(event.Extras, "{{ .JSONName }}")
		{{ end -}}
	}
	{{ end -}}
}

// AddNonColumnFieldsToExtras adds fields without dedicated columns to Extras.
// Returns nil when there are no extras and no non-column fields to add.
func AddNonColumnFieldsToExtras(event *CloudEventHeader) map[string]any {
	hasNonColumn := false
	{{ range .NonColumnFields -}}
	{{ if eq .Kind "string" -}}
	hasNonColumn = hasNonColumn || event.{{ .FieldName }} != ""
	{{ else if eq .GoType.String "time.Time" -}}
	hasNonColumn = hasNonColumn || !event.{{ .FieldName }}.IsZero()
	{{ else if eq .Kind "slice" -}}
	hasNonColumn = hasNonColumn || len(event.{{ .FieldName }}) > 0
	{{ end -}}
	{{ end -}}
	if !hasNonColumn && len(event.Extras) == 0 {
		return nil
	}

	extras := make(map[string]any, len(event.Extras))
	for k, v := range event.Extras {
		extras[k] = v
	}

	{{ range .NonColumnFields -}}
	{{ if eq .Kind "string" -}}
	if event.{{ .FieldName }} != "" {
		extras["{{ .JSONName }}"] = event.{{ .FieldName }}
	}
	{{ else if eq .GoType.String "time.Time" -}}
	if !event.{{ .FieldName }}.IsZero() {
		extras["{{ .JSONName }}"] = event.{{ .FieldName }}
	}
	{{ else if eq .Kind "slice" -}}
	if len(event.{{ .FieldName }}) > 0 {
		extras["{{ .JSONName }}"] = event.{{ .FieldName }}
	}
	{{ else -}}
	if !isZeroValue(event.{{ .FieldName }}) {
		extras["{{ .JSONName }}"] = event.{{ .FieldName }}
	}
	{{ end -}}
	{{ end -}}
	return extras
}
`
